project:
  type: website
  execute-dir: project

website:
  title: "LaSPUR (Land & Sea Planning Unit Reconcilliation)"

  sidebar:
    style: docked
    search: true

    contents:

      # =====================================================
      # ALAT BANTU LASPUR
      # =====================================================
      - text: "Alat Bantu LaSPUR"
        href: index.qmd

      # =====================================================
      # DATA INPUT
      # =====================================================
      - section: "Data Input"
        contents:
          - section: "1. Analisis SERASI"
            contents:
              - href: serasi/01-tumpang-tindih.qmd
                text: "01 Tumpang Tindih"
              - href: serasi/02-bertetangga.qmd
                text: "02 Bertetangga"
  
          - section: "2. Analisis PADU"
            contents:
              - href: padu/padu-ke.qmd
                text: "PADU-KE"
              - href: padu/padu-hs.qmd
                text: "PADU-HS"
              - href: padu/padu-kl.qmd
                text: "PADU-KL"
              - href: padu/padu-kh.qmd
                text: "PADU-KH"
              - href: padu/padu-rtp.qmd
                text: "PADU-RTp"
              - href: padu/padu-se.qmd
                text: "PADU-SE"
              - href: padu/padu-ki.qmd
                text: "PADU-KI"
              - href: padu/padu-kombinasi.qmd
                text: "PADU-Kombinasi"
  
          - href: padan/padan.qmd
            text: "3. Analisis PADAN"
  
          - section: "4. Penyusunan Alternatif"
            contents:
              - href: alternatif/01-tumpang-tindih.qmd
                text: "01 Tumpang Tindih"
              - href: alternatif/02-bertetangga.qmd
                text: "02 Bertetangga"
  
          - href: rekonsiliasi/rekonsiliasi.qmd
            text: "5. Rekonsiliasi"

      # =====================================================
      # PANDUAN PENGGUNAAN
      # =====================================================
      - text: "Panduan Penggunaan"
        href: guide.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-copy: true
    smooth-scroll: true
    number-sections: true
    link-external-newwindow: true
    link-external-icon: true
    include-after-body: footer.html
    css: styles.css